steps:
  - label: ":llama: Run Tests"
    commands:
      - echo "~~~ Building latest test image"
      - docker-compose -f docker-compose.common.yml build test
      - echo "~~~ Running tests"
      - docker-compose -f docker-compose.common.yml run --use-aliases --service-ports test
    artifact_paths:
      - .pytest_reports/**/*

  - label: ":apple: Run Lint"
    commands:
      - echo "~~~ Building latest lint image"
      - docker-compose -f docker-compose.common.yml build lint
      - echo "~~~ Running lint"
      - docker-compose -f docker-compose.common.yml run lint
