[tool.black]
line-length = 88
target-version = ["py36"]

[tool.isort]
include_trailing_comma=true
lines_between_types=1
line_length=88
multi_line_output=3
use_parentheses=true

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = '-vv --cov=test tests --cov-report xml:/tmp/coverage.xml --cov-report term-missing --cov-fail-under=1'
python_files = 'tests/*.py'
filterwarnings = 'ignore:.*PY_SSIZE_T_CLEAN*:DeprecationWarning'
